"""Governance, country packs and access.

Creates the control layer every later business module depends on: identity,
the fixed role catalogue, server-side sessions, country configuration and the
append-only audit trail.

Seeds only the eleven fixed system roles. No demo users, no sample projects, no
financial data, nothing imported from V1.

Deliberately absent: projects, phases, buildings, units and project access.
Project-scoped access needs a real Project to point at, so it lands in
PR-MVP-02 rather than leaving orphan identifiers here.

Revision ID: 0001_governance_access
Revises: 0000_mvp_baseline
Create Date: 2026-08-28

"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_governance_access"
down_revision: str | Sequence[str] | None = "0000_mvp_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Fixed namespace so that every environment derives the same role ids, and a
#: downgrade followed by an upgrade restores the identifiers it removed.
_ROLE_NAMESPACE = uuid.UUID("6f6d4a1e-6f2b-5c9f-9a3e-1c2d3e4f5a6b")

#: The eleven MVP system roles. There is no custom-role builder: adding a role
#: means a reviewed migration, not a runtime write.
_SYSTEM_ROLES: tuple[tuple[str, str], ...] = (
    ("system_admin", "System Administrator"),
    ("project_manager", "Project Manager"),
    ("design_engineering", "Design / Engineering"),
    ("sales_operations", "Sales Operations"),
    ("sales_advisor", "Sales Advisor"),
    ("legal", "Legal"),
    ("collections", "Collections"),
    ("finance", "Finance"),
    ("approver_cfo", "Approver / CFO"),
    ("executive_viewer", "Executive Viewer"),
    ("auditor", "Auditor"),
)


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("symbol", sa.String(length=8), nullable=True),
        sa.Column("minor_units", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code = upper(code) AND length(code) = 3", name=op.f("ck_currencies_code_upper_alpha3")
        ),
        sa.CheckConstraint(
            "minor_units BETWEEN 0 AND 6", name=op.f("ck_currencies_minor_units_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currencies")),
        sa.UniqueConstraint("code", name=op.f("uq_currencies_code")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("key", name=op.f("uq_roles_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(display_name) > 0", name=op.f("ck_users_display_name_not_blank")
        ),
        sa.CheckConstraint("length(email) > 0", name=op.f("ck_users_email_not_blank")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_users_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email_normalized", name=op.f("uq_users_email_normalized")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_action", "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_entity", "audit_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "country_packs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("default_currency_id", sa.UUID(), nullable=False),
        sa.Column("area_unit", sa.String(length=8), nullable=False),
        sa.Column("fiscal_year_start_month", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "area_unit IN ('sqm', 'sqft')", name=op.f("ck_country_packs_area_unit_allowed")
        ),
        sa.CheckConstraint(
            "country_code = upper(country_code) AND length(country_code) = 2",
            name=op.f("ck_country_packs_country_code_upper_alpha2"),
        ),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12",
            name=op.f("ck_country_packs_fiscal_month_range"),
        ),
        sa.ForeignKeyConstraint(
            ["default_currency_id"],
            ["currencies.id"],
            name=op.f("fk_country_packs_default_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_packs")),
        sa.UniqueConstraint("country_code", name=op.f("uq_country_packs_country_code")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role_id", name="user_role"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_user_sessions_expires_after_created")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "country_approval_thresholds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country_pack_id", sa.UUID(), nullable=False),
        sa.Column("discount_review_rate_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("discount_review_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("pricing_requires_finance_approval", sa.Boolean(), nullable=False),
        sa.Column("pricing_requires_commercial_approval", sa.Boolean(), nullable=False),
        sa.Column("minimum_margin_rate_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column(
            "custom_plan_min_down_payment_rate_fraction",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
        ),
        sa.Column("custom_plan_max_duration_months", sa.Integer(), nullable=True),
        sa.Column(
            "custom_plan_max_post_handover_rate_fraction",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
        ),
        sa.Column(
            "custom_plan_max_npv_cost_rate_fraction",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
        ),
        sa.Column("receipt_reversal_requires_dual_control", sa.Boolean(), nullable=False),
        sa.Column("refund_requires_dual_control", sa.Boolean(), nullable=False),
        sa.Column(
            "construction_variation_review_amount", sa.Numeric(precision=18, scale=2), nullable=True
        ),
        sa.Column(
            "forecast_reset_variance_rate_fraction", sa.Numeric(precision=9, scale=6), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "construction_variation_review_amount IS NULL "
            "OR construction_variation_review_amount >= 0",
            name=op.f("ck_country_approval_thresholds_variation_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "custom_plan_max_duration_months IS NULL "
            "OR (custom_plan_max_duration_months > 0 AND custom_plan_max_duration_months <= 600)",
            name=op.f("ck_country_approval_thresholds_plan_duration_range"),
        ),
        sa.CheckConstraint(
            "custom_plan_max_npv_cost_rate_fraction IS NULL "
            "OR (custom_plan_max_npv_cost_rate_fraction >= 0 "
            "AND custom_plan_max_npv_cost_rate_fraction <= 1)",
            name=op.f("ck_country_approval_thresholds_npv_cost_rate_range"),
        ),
        sa.CheckConstraint(
            "custom_plan_max_post_handover_rate_fraction IS NULL "
            "OR (custom_plan_max_post_handover_rate_fraction >= 0 "
            "AND custom_plan_max_post_handover_rate_fraction <= 1)",
            name=op.f("ck_country_approval_thresholds_post_handover_rate_range"),
        ),
        sa.CheckConstraint(
            "custom_plan_min_down_payment_rate_fraction IS NULL "
            "OR (custom_plan_min_down_payment_rate_fraction >= 0 "
            "AND custom_plan_min_down_payment_rate_fraction <= 1)",
            name=op.f("ck_country_approval_thresholds_min_down_payment_rate_range"),
        ),
        sa.CheckConstraint(
            "discount_review_amount IS NULL OR discount_review_amount >= 0",
            name=op.f("ck_country_approval_thresholds_discount_review_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "discount_review_rate_fraction IS NULL "
            "OR (discount_review_rate_fraction >= 0 AND discount_review_rate_fraction <= 1)",
            name=op.f("ck_country_approval_thresholds_discount_review_rate_range"),
        ),
        sa.CheckConstraint(
            "forecast_reset_variance_rate_fraction IS NULL "
            "OR (forecast_reset_variance_rate_fraction >= 0 "
            "AND forecast_reset_variance_rate_fraction <= 1)",
            name=op.f("ck_country_approval_thresholds_forecast_variance_rate_range"),
        ),
        sa.CheckConstraint(
            "minimum_margin_rate_fraction IS NULL "
            "OR (minimum_margin_rate_fraction >= 0 AND minimum_margin_rate_fraction <= 1)",
            name=op.f("ck_country_approval_thresholds_minimum_margin_rate_range"),
        ),
        sa.ForeignKeyConstraint(
            ["country_pack_id"],
            ["country_packs.id"],
            name=op.f("fk_country_approval_thresholds_country_pack_id_country_packs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_approval_thresholds")),
        sa.UniqueConstraint("country_pack_id", name="country_pack"),
        sa.UniqueConstraint(
            "country_pack_id", name=op.f("uq_country_approval_thresholds_country_pack_id")
        ),
    )
    op.create_table(
        "reference_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country_pack_id", sa.UUID(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_reference_values_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["country_pack_id"],
            ["country_packs.id"],
            name=op.f("fk_reference_values_country_pack_id_country_packs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_values")),
    )
    op.create_index(
        op.f("ix_reference_values_country_pack_id"),
        "reference_values",
        ["country_pack_id"],
        unique=False,
    )
    op.create_index(
        "uq_reference_values_country_scope",
        "reference_values",
        ["country_pack_id", "category", "code"],
        unique=True,
        postgresql_where=sa.text("country_pack_id IS NOT NULL"),
    )
    op.create_index(
        "uq_reference_values_global_scope",
        "reference_values",
        ["category", "code"],
        unique=True,
        postgresql_where=sa.text("country_pack_id IS NULL"),
    )
    op.create_table(
        "tax_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country_pack_id", sa.UUID(), nullable=False),
        sa.Column("tax_code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("applies_to", sa.String(length=32), nullable=False),
        sa.Column("calculation_basis", sa.String(length=32), nullable=False),
        sa.Column("rate_fraction", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applies_to IN ('sale', 'rental', 'service_charge', 'construction', 'other')",
            name=op.f("ck_tax_rules_applies_to_allowed"),
        ),
        sa.CheckConstraint(
            "calculation_basis IN ('net_amount', 'gross_amount')",
            name=op.f("ck_tax_rules_calculation_basis_allowed"),
        ),
        sa.CheckConstraint(
            "rate_fraction >= 0 AND rate_fraction <= 1",
            name=op.f("ck_tax_rules_rate_fraction_range"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name=op.f("ck_tax_rules_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["country_pack_id"],
            ["country_packs.id"],
            name=op.f("fk_tax_rules_country_pack_id_country_packs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_rules")),
    )
    op.create_index(
        op.f("ix_tax_rules_country_pack_id"), "tax_rules", ["country_pack_id"], unique=False
    )
    # ### end Alembic commands ###

    _seed_system_roles()


def _seed_system_roles() -> None:
    """Insert the fixed role catalogue.

    This is configuration the application cannot run without, not sample data.
    """
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("key", sa.String()),
        sa.column("label", sa.String()),
    )
    op.bulk_insert(
        roles_table,
        [
            {"id": uuid.uuid5(_ROLE_NAMESPACE, key), "key": key, "label": label}
            for key, label in _SYSTEM_ROLES
        ],
    )


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tax_rules_country_pack_id"), table_name="tax_rules")
    op.drop_table("tax_rules")
    op.drop_index(
        "uq_reference_values_global_scope",
        table_name="reference_values",
        postgresql_where=sa.text("country_pack_id IS NULL"),
    )
    op.drop_index(
        "uq_reference_values_country_scope",
        table_name="reference_values",
        postgresql_where=sa.text("country_pack_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_reference_values_country_pack_id"), table_name="reference_values")
    op.drop_table("reference_values")
    op.drop_table("country_approval_thresholds")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("user_roles")
    op.drop_table("country_packs")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_action", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("currencies")
    # ### end Alembic commands ###
