"""Project, land and permits

Revision ID: 0002_project_land_permits
Revises: 0001_governance_access
Create Date: 2026-08-28 12:01:10.634483+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_project_land_permits"
down_revision: str | Sequence[str] | None = "0001_governance_access"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("developer_entity", sa.String(length=200), nullable=False),
        sa.Column("country_pack_id", sa.UUID(), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("project_type_code", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("base_currency_id", sa.UUID(), nullable=False),
        sa.Column("reporting_currency_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year_start_month", sa.Integer(), nullable=False),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_completion", sa.Date(), nullable=True),
        sa.Column("project_manager_user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('setup', 'predevelopment', 'active', 'on_hold', 'completed', 'cancelled')",
            name=op.f("ck_projects_status_allowed"),
        ),
        sa.CheckConstraint("code = upper(code)", name=op.f("ck_projects_code_upper")),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12", name=op.f("ck_projects_fiscal_month_range")
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name=op.f("ck_projects_latitude_range"),
        ),
        sa.CheckConstraint("length(code) > 0", name=op.f("ck_projects_code_not_blank")),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_projects_name_not_blank")),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name=op.f("ck_projects_longitude_range"),
        ),
        sa.CheckConstraint(
            "planned_start IS NULL OR planned_completion IS NULL "
            "OR planned_completion >= planned_start",
            name=op.f("ck_projects_planned_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["base_currency_id"],
            ["currencies.id"],
            name=op.f("fk_projects_base_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["country_pack_id"],
            ["country_packs.id"],
            name=op.f("fk_projects_country_pack_id_country_packs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_projects_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_manager_user_id"],
            ["users.id"],
            name=op.f("fk_projects_project_manager_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reporting_currency_id"],
            ["currencies.id"],
            name=op.f("fk_projects_reporting_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("code", name=op.f("uq_projects_code")),
    )
    op.create_index(
        op.f("ix_projects_country_pack_id"), "projects", ["country_pack_id"], unique=False
    )
    op.create_index("ix_projects_status", "projects", ["status"], unique=False)
    op.create_table(
        "land_parcels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("plot_number", sa.String(length=64), nullable=False),
        sa.Column("title_deed_number", sa.String(length=120), nullable=True),
        sa.Column("cadastral_reference", sa.String(length=120), nullable=True),
        sa.Column("land_area", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("area_unit", sa.String(length=8), nullable=False),
        sa.Column("ownership_type_code", sa.String(length=64), nullable=True),
        sa.Column("ownership_share_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("acquisition_date", sa.Date(), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("acquisition_fees", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("seller", sa.String(length=200), nullable=True),
        sa.Column("title_status_code", sa.String(length=64), nullable=True),
        sa.Column("zoning_class_code", sa.String(length=64), nullable=True),
        sa.Column("frontage", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("road_access", sa.String(length=500), nullable=True),
        sa.Column("topography", sa.String(length=500), nullable=True),
        sa.Column("geotechnical_status", sa.String(length=500), nullable=True),
        sa.Column("contamination_status", sa.String(length=500), nullable=True),
        sa.Column("flood_drainage_status", sa.String(length=500), nullable=True),
        sa.Column("archaeology_heritage_status", sa.String(length=500), nullable=True),
        sa.Column("power_available", sa.Boolean(), nullable=True),
        sa.Column("water_available", sa.Boolean(), nullable=True),
        sa.Column("sewer_available", sa.Boolean(), nullable=True),
        sa.Column("stormwater_available", sa.Boolean(), nullable=True),
        sa.Column("telecom_available", sa.Boolean(), nullable=True),
        sa.Column("utility_notes", sa.String(length=2000), nullable=True),
        sa.Column("easements", sa.String(length=2000), nullable=True),
        sa.Column("encroachments", sa.String(length=2000), nullable=True),
        sa.Column("constraints_notes", sa.String(length=2000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "area_unit IN ('sqm', 'sqft')", name=op.f("ck_land_parcels_area_unit_allowed")
        ),
        sa.CheckConstraint(
            "acquisition_fees IS NULL OR acquisition_fees >= 0",
            name=op.f("ck_land_parcels_fees_non_negative"),
        ),
        sa.CheckConstraint(
            "frontage IS NULL OR frontage >= 0", name=op.f("ck_land_parcels_frontage_non_negative")
        ),
        sa.CheckConstraint("land_area > 0", name=op.f("ck_land_parcels_land_area_positive")),
        sa.CheckConstraint("length(plot_number) > 0", name=op.f("ck_land_parcels_plot_not_blank")),
        sa.CheckConstraint(
            "ownership_share_fraction IS NULL "
            "OR (ownership_share_fraction > 0 AND ownership_share_fraction <= 1)",
            name=op.f("ck_land_parcels_share_range"),
        ),
        sa.CheckConstraint(
            "purchase_price IS NULL OR purchase_price >= 0",
            name=op.f("ck_land_parcels_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_land_parcels_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_land_parcels")),
        sa.UniqueConstraint(
            "project_id", "plot_number", name=op.f("uq_land_parcels_project_id_plot_number")
        ),
    )
    op.create_index(
        op.f("ix_land_parcels_project_id"), "land_parcels", ["project_id"], unique=False
    )
    op.create_table(
        "user_project_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_user_project_access_granted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_user_project_access_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_user_id"],
            ["users.id"],
            name=op.f("fk_user_project_access_revoked_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_project_access_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_project_access")),
        sa.UniqueConstraint(
            "project_id", "user_id", name=op.f("uq_user_project_access_project_id_user_id")
        ),
    )
    op.create_index(
        "ix_user_project_access_user_id", "user_project_access", ["user_id"], unique=False
    )
    op.create_table(
        "permits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parcel_id", sa.UUID(), nullable=True),
        sa.Column("permit_code", sa.String(length=64), nullable=False),
        sa.Column("permit_type_code", sa.String(length=64), nullable=False),
        sa.Column("authority", sa.String(length=200), nullable=False),
        sa.Column("authority_reference", sa.String(length=120), nullable=True),
        sa.Column("prerequisite_permit_id", sa.UUID(), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("consultant", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_effective_date", sa.Date(), nullable=False),
        sa.Column("planned_submission_date", sa.Date(), nullable=True),
        sa.Column("forecast_submission_date", sa.Date(), nullable=True),
        sa.Column("actual_submission_date", sa.Date(), nullable=True),
        sa.Column("accepted_for_review_date", sa.Date(), nullable=True),
        sa.Column("comments_received_date", sa.Date(), nullable=True),
        sa.Column("resubmission_date", sa.Date(), nullable=True),
        sa.Column("planned_issue_date", sa.Date(), nullable=True),
        sa.Column("forecast_issue_date", sa.Date(), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("renewal_date", sa.Date(), nullable=True),
        sa.Column("statutory_sla_days", sa.Integer(), nullable=True),
        sa.Column("fee_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("conditions", sa.String(length=4000), nullable=True),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("is_critical_path", sa.Boolean(), nullable=False),
        sa.Column("next_action", sa.String(length=500), nullable=True),
        sa.Column("escalation_owner_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('not_started', 'preparing', 'submitted', "
            "'accepted_for_review', 'comments_received', 'resubmission', "
            "'approved_with_conditions', 'issued', 'expired', 'renewed', "
            "'rejected', 'on_hold', 'withdrawn')",
            name=op.f("ck_permits_status_allowed"),
        ),
        sa.CheckConstraint(
            "fee_amount IS NULL OR fee_amount >= 0", name=op.f("ck_permits_fee_non_negative")
        ),
        sa.CheckConstraint("length(permit_code) > 0", name=op.f("ck_permits_code_not_blank")),
        sa.CheckConstraint("prerequisite_permit_id <> id", name=op.f("ck_permits_prereq_not_self")),
        sa.CheckConstraint(
            "statutory_sla_days IS NULL OR statutory_sla_days > 0",
            name=op.f("ck_permits_sla_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["escalation_owner_user_id"],
            ["users.id"],
            name=op.f("fk_permits_escalation_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_permits_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["land_parcels.id"],
            name=op.f("fk_permits_parcel_id_land_parcels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_permit_id"],
            ["permits.id"],
            name=op.f("fk_permits_prerequisite_permit_id_permits"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_permits_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permits")),
        sa.UniqueConstraint(
            "project_id", "permit_code", name=op.f("uq_permits_project_id_permit_code")
        ),
    )
    op.create_index("ix_permits_owner_user_id", "permits", ["owner_user_id"], unique=False)
    op.create_index(
        "ix_permits_project_blocking", "permits", ["project_id", "is_blocking"], unique=False
    )
    op.create_index(
        "ix_permits_project_critical", "permits", ["project_id", "is_critical_path"], unique=False
    )
    op.create_index(op.f("ix_permits_project_id"), "permits", ["project_id"], unique=False)
    op.create_index("ix_permits_status", "permits", ["status"], unique=False)
    op.create_table(
        "planning_controls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parcel_id", sa.UUID(), nullable=False),
        sa.Column("permitted_uses", sa.String(length=2000), nullable=True),
        sa.Column("site_coverage_rate_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("far_ratio", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("maximum_gfa", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("maximum_floors", sa.Integer(), nullable=True),
        sa.Column("maximum_height", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("front_setback", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("side_setback", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("rear_setback", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("parking_requirement", sa.String(length=500), nullable=True),
        sa.Column("minimum_plot_area", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("minimum_frontage", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("density", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("exclusions", sa.String(length=2000), nullable=True),
        sa.Column("variance_required", sa.Boolean(), nullable=False),
        sa.Column("variance_notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "density IS NULL OR density >= 0", name=op.f("ck_planning_controls_density_non_neg")
        ),
        sa.CheckConstraint(
            "far_ratio IS NULL OR far_ratio >= 0",
            name=op.f("ck_planning_controls_far_non_negative"),
        ),
        sa.CheckConstraint(
            "front_setback IS NULL OR front_setback >= 0",
            name=op.f("ck_planning_controls_front_non_neg"),
        ),
        sa.CheckConstraint(
            "maximum_floors IS NULL OR maximum_floors > 0",
            name=op.f("ck_planning_controls_floors_positive"),
        ),
        sa.CheckConstraint(
            "maximum_gfa IS NULL OR maximum_gfa >= 0",
            name=op.f("ck_planning_controls_gfa_non_negative"),
        ),
        sa.CheckConstraint(
            "maximum_height IS NULL OR maximum_height >= 0",
            name=op.f("ck_planning_controls_height_non_neg"),
        ),
        sa.CheckConstraint(
            "minimum_frontage IS NULL OR minimum_frontage >= 0",
            name=op.f("ck_planning_controls_min_frontage_non_neg"),
        ),
        sa.CheckConstraint(
            "minimum_plot_area IS NULL OR minimum_plot_area >= 0",
            name=op.f("ck_planning_controls_min_area_non_neg"),
        ),
        sa.CheckConstraint(
            "rear_setback IS NULL OR rear_setback >= 0",
            name=op.f("ck_planning_controls_rear_non_neg"),
        ),
        sa.CheckConstraint(
            "side_setback IS NULL OR side_setback >= 0",
            name=op.f("ck_planning_controls_side_non_neg"),
        ),
        sa.CheckConstraint(
            "site_coverage_rate_fraction IS NULL "
            "OR (site_coverage_rate_fraction >= 0 AND site_coverage_rate_fraction <= 1)",
            name=op.f("ck_planning_controls_coverage_range"),
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["land_parcels.id"],
            name=op.f("fk_planning_controls_parcel_id_land_parcels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_planning_controls_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planning_controls")),
        sa.UniqueConstraint("parcel_id", name=op.f("uq_planning_controls_parcel_id")),
    )
    op.create_index(
        op.f("ix_planning_controls_project_id"), "planning_controls", ["project_id"], unique=False
    )
    op.create_table(
        "document_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parcel_id", sa.UUID(), nullable=True),
        sa.Column("permit_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("document_type_code", sa.String(length=64), nullable=False),
        sa.Column("reference_number", sa.String(length=120), nullable=True),
        sa.Column("external_url", sa.String(length=2000), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(title) > 0", name=op.f("ck_document_references_title_not_blank")
        ),
        sa.CheckConstraint(
            "parcel_id IS NULL OR permit_id IS NULL",
            name=op.f("ck_document_references_single_attachment"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_document_references_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["land_parcels.id"],
            name=op.f("fk_document_references_parcel_id_land_parcels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["permits.id"],
            name=op.f("fk_document_references_permit_id_permits"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_document_references_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_references")),
    )
    op.create_index(
        "ix_document_references_parcel_id", "document_references", ["parcel_id"], unique=False
    )
    op.create_index(
        "ix_document_references_permit_id", "document_references", ["permit_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_references_project_id"),
        "document_references",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "permit_status_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("permit_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=False),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("changed_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IN ('not_started', 'preparing', 'submitted', "
            "'accepted_for_review', 'comments_received', 'resubmission', "
            "'approved_with_conditions', 'issued', 'expired', 'renewed', "
            "'rejected', 'on_hold', 'withdrawn')",
            name=op.f("ck_permit_status_events_from_allowed"),
        ),
        sa.CheckConstraint(
            "to_status IN ('not_started', 'preparing', 'submitted', "
            "'accepted_for_review', 'comments_received', 'resubmission', "
            "'approved_with_conditions', 'issued', 'expired', 'renewed', "
            "'rejected', 'on_hold', 'withdrawn')",
            name=op.f("ck_permit_status_events_to_allowed"),
        ),
        sa.CheckConstraint(
            "from_status <> to_status", name=op.f("ck_permit_status_events_status_changed")
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_permit_status_events_changed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["permits.id"],
            name=op.f("fk_permit_status_events_permit_id_permits"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permit_status_events")),
    )
    op.create_index(
        op.f("ix_permit_status_events_permit_id"),
        "permit_status_events",
        ["permit_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permit_status_events_permit_id"), table_name="permit_status_events")
    op.drop_table("permit_status_events")
    op.drop_index(op.f("ix_document_references_project_id"), table_name="document_references")
    op.drop_index("ix_document_references_permit_id", table_name="document_references")
    op.drop_index("ix_document_references_parcel_id", table_name="document_references")
    op.drop_table("document_references")
    op.drop_index(op.f("ix_planning_controls_project_id"), table_name="planning_controls")
    op.drop_table("planning_controls")
    op.drop_index("ix_permits_status", table_name="permits")
    op.drop_index(op.f("ix_permits_project_id"), table_name="permits")
    op.drop_index("ix_permits_project_critical", table_name="permits")
    op.drop_index("ix_permits_project_blocking", table_name="permits")
    op.drop_index("ix_permits_owner_user_id", table_name="permits")
    op.drop_table("permits")
    op.drop_index("ix_user_project_access_user_id", table_name="user_project_access")
    op.drop_table("user_project_access")
    op.drop_index(op.f("ix_land_parcels_project_id"), table_name="land_parcels")
    op.drop_table("land_parcels")
    op.drop_index("ix_projects_status", table_name="projects")
    op.drop_index(op.f("ix_projects_country_pack_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
