"""Pricing, price versions and market benchmarks.

Adds the eight tables PR-MVP-04 needs and nothing else. No existing table is
altered: ``units.pricing_approved`` already exists — PR-MVP-03 created it as a
release gate with no writer — and this PR gives it one in code rather than in
the schema.

Additive throughout, so an upgrade cannot disturb a project, a permit or a unit
already loaded. The downgrade drops only what this revision created; inventory
and everything beneath it is untouched, and a rollback loses only pricing
entered after the deploy.

Two partial unique indexes carry invariants no CHECK can express — one active
pricing configuration per project, one active price per unit — and a third,
with NULLs treated as equal, refuses a second active market benchmark at the
same scope. Those are the backstops behind the row locks the service takes;
neither is sufficient alone.

Revision ID: 0004_pricing
Revises: 0003_inventory
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_pricing"
down_revision: str | Sequence[str] | None = "0003_inventory"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("pricing_currency_id", sa.UUID(), nullable=False),
        sa.Column("base_internal_rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("premium_stacking_default", sa.String(length=16), nullable=False),
        sa.Column("maximum_premium_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("offer_valid_days", sa.Integer(), nullable=True),
        sa.Column("price_lock_days", sa.Integer(), nullable=True),
        sa.Column("reservation_expiry_days", sa.Integer(), nullable=True),
        sa.Column(
            "default_payment_plan_adjustment_fraction",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
        ),
        sa.Column("tax_treatment_code", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "premium_stacking_default IN ('additive', 'compound')",
            name=op.f("ck_pricing_configurations_stacking_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved', 'active', 'superseded')",
            name=op.f("ck_pricing_configurations_status_allowed"),
        ),
        sa.CheckConstraint(
            "tax_treatment_code IN ('exclusive', 'inclusive')",
            name=op.f("ck_pricing_configurations_tax_allowed"),
        ),
        sa.CheckConstraint(
            "base_internal_rate >= 0", name=op.f("ck_pricing_configurations_rate_nonneg")
        ),
        sa.CheckConstraint(
            "default_payment_plan_adjustment_fraction IS NULL OR "
            "(default_payment_plan_adjustment_fraction >= -1 AND "
            "default_payment_plan_adjustment_fraction <= 1)",
            name=op.f("ck_pricing_configurations_plan_adjust_range"),
        ),
        sa.CheckConstraint(
            "length(name) > 0", name=op.f("ck_pricing_configurations_name_not_blank")
        ),
        sa.CheckConstraint(
            "maximum_premium_fraction IS NULL OR (maximum_premium_fraction >= 0 AND "
            "maximum_premium_fraction <= 1)",
            name=op.f("ck_pricing_configurations_cap_range"),
        ),
        sa.CheckConstraint(
            "offer_valid_days IS NULL OR offer_valid_days > 0",
            name=op.f("ck_pricing_configurations_offer_days_positive"),
        ),
        sa.CheckConstraint(
            "price_lock_days IS NULL OR price_lock_days > 0",
            name=op.f("ck_pricing_configurations_lock_days_positive"),
        ),
        sa.CheckConstraint(
            "reservation_expiry_days IS NULL OR reservation_expiry_days > 0",
            name=op.f("ck_pricing_configurations_expiry_days_positive"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_pricing_configurations_valid_range"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_pricing_configurations_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["activated_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_configurations_activated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_configurations_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_configurations_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_currency_id"],
            ["currencies.id"],
            name=op.f("fk_pricing_configurations_pricing_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_pricing_configurations_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_configurations_submitted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_configurations")),
        sa.UniqueConstraint("id", "project_id", name="config_project"),
        sa.UniqueConstraint(
            "project_id",
            "version_number",
            name=op.f("uq_pricing_configurations_project_id_version_number"),
        ),
    )
    op.create_index(
        "ix_pricing_configurations_project_id_status",
        "pricing_configurations",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_pricing_configurations_active",
        "pricing_configurations",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "market_benchmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("unit_type_code", sa.String(length=64), nullable=True),
        sa.Column("area_basis", sa.String(length=16), nullable=False),
        sa.Column("benchmark_price_per_area", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency_id", sa.UUID(), nullable=False),
        sa.Column("comparison_date", sa.Date(), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("tolerance_fraction", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "area_basis IN ('internal', 'weighted')",
            name=op.f("ck_market_benchmarks_basis_allowed"),
        ),
        sa.CheckConstraint(
            "benchmark_price_per_area > 0", name=op.f("ck_market_benchmarks_price_positive")
        ),
        sa.CheckConstraint(
            "length(source_name) > 0", name=op.f("ck_market_benchmarks_source_not_blank")
        ),
        sa.CheckConstraint(
            "tolerance_fraction >= 0 AND tolerance_fraction <= 1",
            name=op.f("ck_market_benchmarks_tolerance_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_market_benchmarks_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_market_benchmarks_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["phase_id", "project_id"],
            ["phases.id", "phases.project_id"],
            name="phase",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="project", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_benchmarks")),
        sa.UniqueConstraint("id", "project_id", name="benchmark_project"),
    )
    op.create_index(
        "uq_market_benchmarks_scope",
        "market_benchmarks",
        ["project_id", "phase_id", "unit_type_code"],
        unique=True,
        postgresql_where=sa.text("is_active"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "pricing_area_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("pricing_configuration_id", sa.UUID(), nullable=False),
        sa.Column("area_type_id", sa.UUID(), nullable=False),
        sa.Column("pricing_method", sa.String(length=32), nullable=False),
        sa.Column("rate_per_area", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("internal_rate_factor", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(pricing_method = 'fixed_rate_per_area'   AND rate_per_area IS NOT NULL AND "
            "internal_rate_factor IS NULL) OR (pricing_method = 'factor_of_internal_rate'   AND "
            "internal_rate_factor IS NOT NULL AND rate_per_area IS NULL) OR (pricing_method IN "
            "('internal_base', 'excluded')   AND rate_per_area IS NULL AND internal_rate_factor "
            "IS NULL)",
            name=op.f("ck_pricing_area_rules_method_inputs"),
        ),
        sa.CheckConstraint(
            "pricing_method IN ('internal_base', 'fixed_rate_per_area', "
            "'factor_of_internal_rate', 'excluded')",
            name=op.f("ck_pricing_area_rules_method_allowed"),
        ),
        sa.CheckConstraint(
            "internal_rate_factor IS NULL OR internal_rate_factor >= 0",
            name=op.f("ck_pricing_area_rules_factor_nonneg"),
        ),
        sa.CheckConstraint(
            "rate_per_area IS NULL OR rate_per_area >= 0",
            name=op.f("ck_pricing_area_rules_rate_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["area_type_id", "project_id"],
            ["area_types.id", "area_types.project_id"],
            name="area_type",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_area_rules_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_configuration_id", "project_id"],
            ["pricing_configurations.id", "pricing_configurations.project_id"],
            name="config",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_area_rules")),
        sa.UniqueConstraint("id", "project_id", name="area_rule_project"),
        sa.UniqueConstraint(
            "pricing_configuration_id",
            "area_type_id",
            name=op.f("uq_pricing_area_rules_pricing_configuration_id_area_type_id"),
        ),
    )
    op.create_index(
        "ix_pricing_area_rules_configuration_id",
        "pricing_area_rules",
        ["pricing_configuration_id"],
        unique=False,
    )
    op.create_table(
        "pricing_escalation_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("pricing_configuration_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("phase_id", sa.UUID(), nullable=True),
        sa.Column("unit_type_code", sa.String(length=64), nullable=True),
        sa.Column("threshold_date", sa.Date(), nullable=True),
        sa.Column("threshold_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("milestone_reference", sa.String(length=200), nullable=True),
        sa.Column("market_index_reference", sa.String(length=200), nullable=True),
        sa.Column("adjustment_method", sa.String(length=16), nullable=False),
        sa.Column(
            "adjustment_percentage_fraction", sa.Numeric(precision=9, scale=6), nullable=True
        ),
        sa.Column("adjustment_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("cumulative", sa.Boolean(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(adjustment_method = 'percentage' AND adjustment_percentage_fraction IS NOT NULL "
            "AND adjustment_amount IS NULL) OR (adjustment_method = 'fixed' AND adjustment_amount "
            "IS NOT NULL   AND adjustment_percentage_fraction IS NULL)",
            name=op.f("ck_pricing_escalation_rules_method_inputs"),
        ),
        sa.CheckConstraint(
            "(scope_type = 'phase' AND phase_id IS NOT NULL AND unit_type_code IS NULL) OR "
            "(scope_type = 'unit_type' AND unit_type_code IS NOT NULL AND phase_id IS NULL) OR "
            "(scope_type = 'project' AND phase_id IS NULL AND unit_type_code IS NULL)",
            name=op.f("ck_pricing_escalation_rules_scope_inputs"),
        ),
        sa.CheckConstraint(
            "(trigger_type = 'date' AND threshold_date IS NOT NULL) OR trigger_type <> 'date'",
            name=op.f("ck_pricing_escalation_rules_date_trigger_has_date"),
        ),
        sa.CheckConstraint(
            "adjustment_method IN ('percentage', 'fixed')",
            name=op.f("ck_pricing_escalation_rules_method_allowed"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('project', 'phase', 'unit_type')",
            name=op.f("ck_pricing_escalation_rules_scope_allowed"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('date', 'sales_percentage', 'construction_milestone', "
            "'market_index')",
            name=op.f("ck_pricing_escalation_rules_trigger_allowed"),
        ),
        sa.CheckConstraint(
            "adjustment_percentage_fraction IS NULL OR (adjustment_percentage_fraction >= -1 AND "
            "adjustment_percentage_fraction <= 1)",
            name=op.f("ck_pricing_escalation_rules_percentage_range"),
        ),
        sa.CheckConstraint(
            "code = upper(code)", name=op.f("ck_pricing_escalation_rules_code_upper")
        ),
        sa.CheckConstraint(
            "length(code) > 0", name=op.f("ck_pricing_escalation_rules_code_not_blank")
        ),
        sa.CheckConstraint(
            "threshold_fraction IS NULL OR (threshold_fraction >= 0 AND threshold_fraction <= 1)",
            name=op.f("ck_pricing_escalation_rules_threshold_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_escalation_rules_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["phase_id", "project_id"],
            ["phases.id", "phases.project_id"],
            name="phase",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_configuration_id", "project_id"],
            ["pricing_configurations.id", "pricing_configurations.project_id"],
            name="config",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_escalation_rules")),
        sa.UniqueConstraint("id", "project_id", name="escalation_rule_project"),
        sa.UniqueConstraint(
            "pricing_configuration_id",
            "code",
            name=op.f("uq_pricing_escalation_rules_pricing_configuration_id_code"),
        ),
    )
    op.create_index(
        "ix_pricing_escalation_rules_config_id",
        "pricing_escalation_rules",
        ["pricing_configuration_id"],
        unique=False,
    )
    op.create_table(
        "pricing_premium_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("pricing_configuration_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("match_code", sa.String(length=64), nullable=True),
        sa.Column("custom_field_definition_id", sa.UUID(), nullable=True),
        sa.Column("custom_option_code", sa.String(length=64), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("percentage_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("eligible_base", sa.String(length=32), nullable=False),
        sa.Column("stacking_method", sa.String(length=16), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(method = 'percentage' AND percentage_fraction IS NOT NULL AND amount IS NULL) OR "
            "(method <> 'percentage' AND amount IS NOT NULL AND percentage_fraction IS NULL)",
            name=op.f("ck_pricing_premium_rules_method_inputs"),
        ),
        sa.CheckConstraint(
            "(source_kind = 'custom_field' AND custom_field_definition_id IS NOT NULL) OR "
            "(source_kind <> 'custom_field' AND custom_field_definition_id IS NULL     AND "
            "custom_option_code IS NULL)",
            name=op.f("ck_pricing_premium_rules_custom_field_inputs"),
        ),
        sa.CheckConstraint(
            "eligible_base IN ('base_area_value', 'base_with_adjustments')",
            name=op.f("ck_pricing_premium_rules_base_allowed"),
        ),
        sa.CheckConstraint(
            "method IN ('percentage', 'fixed', 'per_area', 'fixed_per_asset')",
            name=op.f("ck_pricing_premium_rules_method_allowed"),
        ),
        sa.CheckConstraint(
            "source_kind IN ('phase', 'building', 'unit_type', 'view_class', 'floor_band', "
            "'orientation', 'corner', 'pool_access', 'accessibility', 'garden_class', 'parking', "
            "'storage', 'area_type', 'custom_field')",
            name=op.f("ck_pricing_premium_rules_source_allowed"),
        ),
        sa.CheckConstraint(
            "stacking_method IS NULL OR stacking_method IN ('additive', 'compound')",
            name=op.f("ck_pricing_premium_rules_stacking_allowed"),
        ),
        sa.CheckConstraint("code = upper(code)", name=op.f("ck_pricing_premium_rules_code_upper")),
        sa.CheckConstraint(
            "length(code) > 0", name=op.f("ck_pricing_premium_rules_code_not_blank")
        ),
        sa.CheckConstraint(
            "length(label) > 0", name=op.f("ck_pricing_premium_rules_label_not_blank")
        ),
        sa.CheckConstraint(
            "percentage_fraction IS NULL OR (percentage_fraction >= -1 AND percentage_fraction <= "
            "1)",
            name=op.f("ck_pricing_premium_rules_percentage_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_premium_rules_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["custom_field_definition_id"],
            ["custom_field_definitions.id"],
            name="custom_field",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_configuration_id", "project_id"],
            ["pricing_configurations.id", "pricing_configurations.project_id"],
            name="config",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_premium_rules")),
        sa.UniqueConstraint("id", "project_id", name="premium_rule_project"),
        sa.UniqueConstraint(
            "pricing_configuration_id",
            "code",
            name=op.f("uq_pricing_premium_rules_pricing_configuration_id_code"),
        ),
    )
    op.create_index(
        "ix_pricing_premium_rules_configuration_id",
        "pricing_premium_rules",
        ["pricing_configuration_id"],
        unique=False,
    )
    op.create_table(
        "pricing_escalation_activations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("pricing_escalation_rule_id", sa.UUID(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("evidence_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("evidence_date", sa.Date(), nullable=True),
        sa.Column("evidence_reference", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reversal_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_active OR (reversed_at IS NOT NULL AND reversal_reason IS NOT NULL)",
            name=op.f("ck_pricing_escalation_activations_reversal_complete"),
        ),
        sa.CheckConstraint(
            "length(evidence_reference) > 0",
            name=op.f("ck_pricing_escalation_activations_evidence_not_blank"),
        ),
        sa.CheckConstraint(
            "length(reason) > 0", name=op.f("ck_pricing_escalation_activations_reason_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_escalation_activations_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_escalation_rule_id", "project_id"],
            ["pricing_escalation_rules.id", "pricing_escalation_rules.project_id"],
            name="rule",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_user_id"],
            ["users.id"],
            name=op.f("fk_pricing_escalation_activations_reversed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_escalation_activations")),
        sa.UniqueConstraint("id", "project_id", name="activation_project"),
    )
    op.create_index(
        "ix_pricing_escalation_activations_project_id",
        "pricing_escalation_activations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "uq_pricing_escalation_activations_rule",
        "pricing_escalation_activations",
        ["pricing_escalation_rule_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "unit_price_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("pricing_configuration_id", sa.UUID(), nullable=False),
        sa.Column("unit_area_schedule_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency_id", sa.UUID(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("base_area_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("scope_adjustment_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("premium_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("premium_cap_adjustment", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("escalation_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("paid_upgrade_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reference_price_ex_tax", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("internal_area_snapshot", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("weighted_area_snapshot", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("price_per_internal_area", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("price_per_weighted_area", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("market_benchmark_id", sa.UUID(), nullable=True),
        sa.Column(
            "market_benchmark_price_snapshot", sa.Numeric(precision=18, scale=2), nullable=True
        ),
        sa.Column("market_deviation_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("market_flag", sa.String(length=24), nullable=False),
        sa.Column("basis_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "market_flag IN ('within_tolerance', 'above_tolerance', 'below_tolerance', "
            "'no_benchmark')",
            name=op.f("ck_unit_price_versions_flag_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved', 'active', 'superseded')",
            name=op.f("ck_unit_price_versions_status_allowed"),
        ),
        sa.CheckConstraint("base_area_value >= 0", name=op.f("ck_unit_price_versions_base_nonneg")),
        sa.CheckConstraint(
            "paid_upgrade_total >= 0", name=op.f("ck_unit_price_versions_upgrade_nonneg")
        ),
        sa.CheckConstraint(
            "premium_cap_adjustment <= 0", name=op.f("ck_unit_price_versions_cap_not_positive")
        ),
        sa.CheckConstraint(
            "reference_price_ex_tax >= 0", name=op.f("ck_unit_price_versions_price_nonneg")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name=op.f("ck_unit_price_versions_valid_range"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_unit_price_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["activated_by_user_id"],
            ["users.id"],
            name=op.f("fk_unit_price_versions_activated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_unit_price_versions_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_unit_price_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_unit_price_versions_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["market_benchmark_id", "project_id"],
            ["market_benchmarks.id", "market_benchmarks.project_id"],
            name="benchmark",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_configuration_id", "project_id"],
            ["pricing_configurations.id", "pricing_configurations.project_id"],
            name="config",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_unit_price_versions_submitted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_area_schedule_id", "project_id"],
            ["unit_area_schedules.id", "unit_area_schedules.project_id"],
            name="schedule",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id", "project_id"],
            ["units.id", "units.project_id"],
            name="unit",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_price_versions")),
        sa.UniqueConstraint("id", "project_id", name="version_project"),
        sa.UniqueConstraint(
            "unit_id", "version_number", name=op.f("uq_unit_price_versions_unit_id_version_number")
        ),
    )
    op.create_index(
        "ix_unit_price_versions_project_id_status",
        "unit_price_versions",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_unit_price_versions_unit_id_status",
        "unit_price_versions",
        ["unit_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_unit_price_versions_active",
        "unit_price_versions",
        ["unit_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "unit_price_components",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("unit_price_version_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("component_type", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_of_measure", sa.String(length=16), nullable=True),
        sa.Column("basis_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("rate", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("factor", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("calculated_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("override_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("final_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column("area_rule_id", sa.UUID(), nullable=True),
        sa.Column("premium_rule_id", sa.UUID(), nullable=True),
        sa.Column("escalation_activation_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "component_type IN ('base_internal', 'base_attached', 'scope_adjustment', "
            "'feature_premium', 'sub_asset_premium', 'escalation', 'paid_upgrade', "
            "'premium_cap_adjustment', 'manual_override')",
            name=op.f("ck_unit_price_components_type_allowed"),
        ),
        sa.CheckConstraint(
            "(override_amount IS NULL AND override_reason IS NULL) OR (override_amount IS NOT "
            "NULL AND override_reason IS NOT NULL)",
            name=op.f("ck_unit_price_components_override_complete"),
        ),
        sa.CheckConstraint(
            "final_amount = COALESCE(override_amount, calculated_amount)",
            name=op.f("ck_unit_price_components_final_matches"),
        ),
        sa.CheckConstraint(
            "length(code) > 0", name=op.f("ck_unit_price_components_code_not_blank")
        ),
        sa.CheckConstraint(
            "length(label) > 0", name=op.f("ck_unit_price_components_label_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["area_rule_id", "project_id"],
            ["pricing_area_rules.id", "pricing_area_rules.project_id"],
            name="area_rule",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["escalation_activation_id", "project_id"],
            ["pricing_escalation_activations.id", "pricing_escalation_activations.project_id"],
            name="activation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["premium_rule_id", "project_id"],
            ["pricing_premium_rules.id", "pricing_premium_rules.project_id"],
            name="premium_rule",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_price_version_id", "project_id"],
            ["unit_price_versions.id", "unit_price_versions.project_id"],
            name="version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_price_components")),
        sa.UniqueConstraint(
            "unit_price_version_id",
            "sequence",
            name=op.f("uq_unit_price_components_unit_price_version_id_sequence"),
        ),
    )
    op.create_index(
        "ix_unit_price_components_version_id",
        "unit_price_components",
        ["unit_price_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_unit_price_components_version_id", table_name="unit_price_components")
    op.drop_table("unit_price_components")
    op.drop_index(
        "uq_unit_price_versions_active",
        table_name="unit_price_versions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_unit_price_versions_unit_id_status", table_name="unit_price_versions")
    op.drop_index("ix_unit_price_versions_project_id_status", table_name="unit_price_versions")
    op.drop_table("unit_price_versions")
    op.drop_index(
        "uq_pricing_escalation_activations_rule",
        table_name="pricing_escalation_activations",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        "ix_pricing_escalation_activations_project_id", table_name="pricing_escalation_activations"
    )
    op.drop_table("pricing_escalation_activations")
    op.drop_index("ix_pricing_premium_rules_configuration_id", table_name="pricing_premium_rules")
    op.drop_table("pricing_premium_rules")
    op.drop_index("ix_pricing_escalation_rules_config_id", table_name="pricing_escalation_rules")
    op.drop_table("pricing_escalation_rules")
    op.drop_index("ix_pricing_area_rules_configuration_id", table_name="pricing_area_rules")
    op.drop_table("pricing_area_rules")
    op.drop_index(
        "uq_market_benchmarks_scope",
        table_name="market_benchmarks",
        postgresql_where=sa.text("is_active"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("market_benchmarks")
    op.drop_index(
        "uq_pricing_configurations_active",
        table_name="pricing_configurations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "ix_pricing_configurations_project_id_status", table_name="pricing_configurations"
    )
    op.drop_table("pricing_configurations")
    # ### end Alembic commands ###
