"""Payment plans: schedules, versions, instalments and manual triggers.

Additive only. Nothing in ``sale_contracts`` is altered: a sale's governing
schedule is found through ``payment_plans.sale_contract_id``, so the upstream
domain gains no column and no dependency on this one. The downgrade drops
exactly these four tables and leaves sales and legal untouched.

Revision ID: 0006_payment_plans
Revises: 0005_sales_legal
Create Date: 2026-08-30 18:20:11.115917+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_payment_plans"
down_revision: str | Sequence[str] | None = "0005_sales_legal"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("sale_contract_id", sa.UUID(), nullable=False),
        sa.Column("plan_number", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plans_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_payment_plans_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sale_contract_id", "project_id"],
            ["sale_contracts.id", "sale_contracts.project_id"],
            name="sale",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_plans")),
        sa.UniqueConstraint("id", "project_id", name="payment_plan_project"),
        sa.UniqueConstraint("project_id", "plan_number", name="uq_payment_plans_number"),
        sa.UniqueConstraint("sale_contract_id", name="uq_payment_plans_sale"),
    )
    op.create_index("ix_payment_plans_project_id", "payment_plans", ["project_id"], unique=False)
    op.create_table(
        "payment_plan_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("payment_plan_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("currency_id", sa.UUID(), nullable=False),
        sa.Column("contract_value_covered", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_total_snapshot", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("buyer_fee_total_snapshot", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "total_buyer_payable_snapshot", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column("allocation_mode", sa.String(length=16), nullable=False),
        sa.Column("charge_allocation_mode", sa.String(length=16), nullable=False),
        sa.Column("reservation_treatment", sa.String(length=24), nullable=False),
        sa.Column("origin_type", sa.String(length=16), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column("change_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by_user_id", sa.UUID(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "allocation_mode IN ('percentage', 'amount')",
            name=op.f("ck_payment_plan_versions_allocation_ok"),
        ),
        sa.CheckConstraint(
            "charge_allocation_mode IN ('pro_rata', 'manual')",
            name=op.f("ck_payment_plan_versions_charge_ok"),
        ),
        sa.CheckConstraint(
            "origin_type <> 'copied_plan' OR source_version_id IS NOT NULL",
            name=op.f("ck_payment_plan_versions_copied_has_source"),
        ),
        sa.CheckConstraint(
            "origin_type IN ('custom', 'copied_plan')",
            name=op.f("ck_payment_plan_versions_origin_ok"),
        ),
        sa.CheckConstraint(
            "reservation_treatment IN ('included_in_schedule', 'reference_only')",
            name=op.f("ck_payment_plan_versions_reservation_ok"),
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR rejection_reason IS NOT NULL",
            name=op.f("ck_payment_plan_versions_rejected_has_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved', 'active', 'superseded', 'rejected')",
            name=op.f("ck_payment_plan_versions_status_ok"),
        ),
        sa.CheckConstraint(
            "buyer_fee_total_snapshot >= 0", name=op.f("ck_payment_plan_versions_fee_nonneg")
        ),
        sa.CheckConstraint(
            "contract_value_covered >= 0", name=op.f("ck_payment_plan_versions_covered_nonneg")
        ),
        sa.CheckConstraint(
            "tax_total_snapshot >= 0", name=op.f("ck_payment_plan_versions_tax_nonneg")
        ),
        sa.CheckConstraint(
            "total_buyer_payable_snapshot >= 0",
            name=op.f("ck_payment_plan_versions_payable_nonneg"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_payment_plan_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["activated_by_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plan_versions_activated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plan_versions_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plan_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_payment_plan_versions_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_plan_id", "project_id"],
            ["payment_plans.id", "payment_plans.project_id"],
            name="plan",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plan_versions_rejected_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id", "project_id"],
            ["payment_plan_versions.id", "payment_plan_versions.project_id"],
            name="source",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plan_versions_submitted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_plan_versions")),
        sa.UniqueConstraint("id", "project_id", name="plan_version_project"),
        sa.UniqueConstraint("payment_plan_id", "version_number", name="uq_plan_versions_number"),
    )
    op.create_index(
        "ix_plan_versions_plan_status",
        "payment_plan_versions",
        ["payment_plan_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_plan_versions_project_id", "payment_plan_versions", ["project_id"], unique=False
    )
    op.create_index(
        "uq_plan_versions_active",
        "payment_plan_versions",
        ["payment_plan_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_plan_versions_open",
        "payment_plan_versions",
        ["payment_plan_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft', 'submitted', 'approved')"),
    )
    op.create_table(
        "payment_plan_installments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("payment_plan_version_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("trigger_reference", sa.String(length=200), nullable=True),
        sa.Column("offset_days", sa.Integer(), nullable=True),
        sa.Column("recurrence_index", sa.Integer(), nullable=True),
        sa.Column("contractual_due_date", sa.Date(), nullable=True),
        sa.Column("forecast_due_date", sa.Date(), nullable=True),
        sa.Column("actual_due_date", sa.Date(), nullable=True),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column("principal_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("principal_fraction", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fee_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("trigger_status", sa.String(length=24), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger_status IN ('scheduled', 'awaiting_trigger', 'triggered')",
            name=op.f("ck_payment_plan_installments_trigger_status_ok"),
        ),
        sa.CheckConstraint(
            "trigger_type <> 'days_after_spa' OR offset_days IS NOT NULL",
            name=op.f("ck_payment_plan_installments_relative_has_offset"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('fixed_date', 'days_after_spa', 'recurring_monthly', "
            "'recurring_quarterly') OR actual_due_date IS NULL OR trigger_status = 'triggered'",
            name=op.f("ck_payment_plan_installments_contingent_needs_trigger"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('fixed_date', 'days_after_spa', 'recurring_monthly', "
            "'recurring_quarterly', 'construction_milestone', 'handover', 'title_transfer', "
            "'manual_approved_event')",
            name=op.f("ck_payment_plan_installments_trigger_type_ok"),
        ),
        sa.CheckConstraint(
            "trigger_type NOT IN ('fixed_date', 'recurring_monthly', 'recurring_quarterly') OR "
            "contractual_due_date IS NOT NULL",
            name=op.f("ck_payment_plan_installments_dated_has_date"),
        ),
        sa.CheckConstraint("fee_amount >= 0", name=op.f("ck_payment_plan_installments_fee_nonneg")),
        sa.CheckConstraint(
            "grace_days >= 0", name=op.f("ck_payment_plan_installments_grace_nonneg")
        ),
        sa.CheckConstraint(
            "offset_days IS NULL OR offset_days >= 0",
            name=op.f("ck_payment_plan_installments_offset_nonneg"),
        ),
        sa.CheckConstraint(
            "principal_amount >= 0", name=op.f("ck_payment_plan_installments_principal_nonneg")
        ),
        sa.CheckConstraint(
            "principal_fraction >= 0 AND principal_fraction <= 1",
            name=op.f("ck_payment_plan_installments_fraction_range"),
        ),
        sa.CheckConstraint(
            "sequence >= 1", name=op.f("ck_payment_plan_installments_sequence_positive")
        ),
        sa.CheckConstraint("tax_amount >= 0", name=op.f("ck_payment_plan_installments_tax_nonneg")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_payment_plan_installments_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_plan_version_id", "project_id"],
            ["payment_plan_versions.id", "payment_plan_versions.project_id"],
            name="version",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_plan_installments")),
        sa.UniqueConstraint("id", "project_id", name="plan_installment_project"),
        sa.UniqueConstraint("payment_plan_version_id", "sequence", name="uq_installments_sequence"),
    )
    op.create_index(
        "ix_installments_actual_due_date",
        "payment_plan_installments",
        ["actual_due_date"],
        unique=False,
    )
    op.create_index(
        "ix_installments_forecast_due_date",
        "payment_plan_installments",
        ["forecast_due_date"],
        unique=False,
    )
    op.create_index(
        "ix_installments_owner_user_id",
        "payment_plan_installments",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_installments_project_id", "payment_plan_installments", ["project_id"], unique=False
    )
    op.create_index(
        "ix_installments_trigger_status",
        "payment_plan_installments",
        ["trigger_status"],
        unique=False,
    )
    op.create_index(
        "ix_installments_version_sequence",
        "payment_plan_installments",
        ["payment_plan_version_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "installment_trigger_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("installment_id", sa.UUID(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("evidence_reference", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("submitted_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "status <> 'approved' OR approved_by_user_id IS NOT NULL",
            name=op.f("ck_installment_trigger_events_approved_has_approver"),
        ),
        sa.CheckConstraint(
            "status <> 'reversed' OR reversal_reason IS NOT NULL",
            name=op.f("ck_installment_trigger_events_reversed_has_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('submitted', 'approved', 'reversed')",
            name=op.f("ck_installment_trigger_events_status_ok"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_installment_trigger_events_approved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["installment_id", "project_id"],
            ["payment_plan_installments.id", "payment_plan_installments.project_id"],
            name="installment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_user_id"],
            ["users.id"],
            name=op.f("fk_installment_trigger_events_reversed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_installment_trigger_events_submitted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installment_trigger_events")),
        sa.UniqueConstraint("id", "project_id", name="plan_trigger_event_project"),
    )
    op.create_index(
        "ix_trigger_events_installment_id",
        "installment_trigger_events",
        ["installment_id"],
        unique=False,
    )
    op.create_index(
        "ix_trigger_events_project_id", "installment_trigger_events", ["project_id"], unique=False
    )
    op.create_index(
        "uq_trigger_events_standing",
        "installment_trigger_events",
        ["installment_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('submitted', 'approved')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_trigger_events_standing",
        table_name="installment_trigger_events",
        postgresql_where=sa.text("status IN ('submitted', 'approved')"),
    )
    op.drop_index("ix_trigger_events_project_id", table_name="installment_trigger_events")
    op.drop_index("ix_trigger_events_installment_id", table_name="installment_trigger_events")
    op.drop_table("installment_trigger_events")
    op.drop_index("ix_installments_version_sequence", table_name="payment_plan_installments")
    op.drop_index("ix_installments_trigger_status", table_name="payment_plan_installments")
    op.drop_index("ix_installments_project_id", table_name="payment_plan_installments")
    op.drop_index("ix_installments_owner_user_id", table_name="payment_plan_installments")
    op.drop_index("ix_installments_forecast_due_date", table_name="payment_plan_installments")
    op.drop_index("ix_installments_actual_due_date", table_name="payment_plan_installments")
    op.drop_table("payment_plan_installments")
    op.drop_index(
        "uq_plan_versions_open",
        table_name="payment_plan_versions",
        postgresql_where=sa.text("status IN ('draft', 'submitted', 'approved')"),
    )
    op.drop_index(
        "uq_plan_versions_active",
        table_name="payment_plan_versions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_plan_versions_project_id", table_name="payment_plan_versions")
    op.drop_index("ix_plan_versions_plan_status", table_name="payment_plan_versions")
    op.drop_table("payment_plan_versions")
    op.drop_index("ix_payment_plans_project_id", table_name="payment_plans")
    op.drop_table("payment_plans")
    # ### end Alembic commands ###
