"""management_actions

Revision ID: 0018_management_actions
Revises: 0017_consultant_commissions
Create Date: 2026-09-09 04:08:25.683723+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018_management_actions"
down_revision: str | Sequence[str] | None = "0017_consultant_commissions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "management_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_code", sa.String(length=80), nullable=True),
        sa.Column("source_key", sa.String(length=300), nullable=True),
        sa.Column("source_observation_date", sa.Date(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(source_type = 'manual' AND source_code IS NULL AND source_key "
            "IS NULL AND source_observation_date IS NULL) OR (source_type <> "
            "'manual' AND source_code IS NOT NULL AND source_key IS NOT NULL "
            "AND source_observation_date IS NOT NULL)",
            name=op.f("ck_management_actions_source_provenance"),
        ),
        sa.CheckConstraint(
            "(status = 'cancelled') = (cancelled_at IS NOT NULL)",
            name=op.f("ck_management_actions_cancellation_state"),
        ),
        sa.CheckConstraint(
            "(status = 'completed') = (completed_at IS NOT NULL)",
            name=op.f("ck_management_actions_completion_state"),
        ),
        sa.CheckConstraint(
            "source_type IN ('manual', 'portfolio_risk', 'portfolio_outlook')",
            name=op.f("ck_management_actions_source_ok"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_management_actions_status_ok"),
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_management_actions_title_present")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_management_actions_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_management_actions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_management_actions_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_management_actions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_management_actions")),
    )
    op.create_index(
        "ix_ma_owner_status_due",
        "management_actions",
        ["owner_user_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_ma_project_source",
        "management_actions",
        ["project_id", "source_type", "source_key"],
        unique=False,
    )
    op.create_index(
        "ix_ma_project_status_due",
        "management_actions",
        ["project_id", "status", "due_date"],
        unique=False,
    )
    op.create_table(
        "management_action_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('created', 'updated', 'status_changed', 'reopened')",
            name=op.f("ck_management_action_history_event_ok"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_management_action_history_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["management_actions.id"],
            name=op.f("fk_management_action_history_action_id_management_actions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_management_action_history_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_management_action_history")),
        sa.UniqueConstraint(
            "action_id", "version", name=op.f("uq_management_action_history_action_id_version")
        ),
    )
    op.execute("""
        CREATE FUNCTION management_action_history_immutable() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Management action history is append-only';
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER management_action_history_immutable
        BEFORE UPDATE OR DELETE ON management_action_history
        FOR EACH ROW EXECUTE FUNCTION management_action_history_immutable()
    """)


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS management_action_history_immutable ON management_action_history"
    )
    op.execute("DROP FUNCTION IF EXISTS management_action_history_immutable()")
    op.drop_table("management_action_history")
    op.drop_index("ix_ma_project_status_due", table_name="management_actions")
    op.drop_index("ix_ma_project_source", table_name="management_actions")
    op.drop_index("ix_ma_owner_status_due", table_name="management_actions")
    op.drop_table("management_actions")
    # ### end Alembic commands ###
