"""management_reporting

Revision ID: 0020_management_reporting
Revises: 0019_management_actions
Create Date: 2026-09-10 03:42:33.830899+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0020_management_reporting"
down_revision: str | Sequence[str] | None = "0019_management_actions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "management_report_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("creator_display_name", sa.String(length=200), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("project_count", sa.Integer(), nullable=False),
        sa.Column("incomplete_project_count", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(scope_type = 'project') = (project_id IS NOT NULL)",
            name=op.f("ck_management_report_snapshots_project_scope"),
        ),
        sa.CheckConstraint(
            "as_of_date = (captured_at AT TIME ZONE 'UTC')::date",
            name=op.f("ck_management_report_snapshots_capture_date"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_management_report_snapshots_hash_sha256"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'",
            name=op.f("ck_management_report_snapshots_payload_object"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('portfolio', 'project')",
            name=op.f("ck_management_report_snapshots_scope_ok"),
        ),
        sa.CheckConstraint(
            "project_count > 0 AND incomplete_project_count BETWEEN 0 AND project_count",
            name=op.f("ck_management_report_snapshots_counts_ok"),
        ),
        sa.CheckConstraint(
            "schema_version > 0", name=op.f("ck_management_report_snapshots_schema_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_management_report_snapshots_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_management_report_snapshots_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_management_report_snapshots")),
    )
    op.create_index(
        "ix_mrs_captured", "management_report_snapshots", ["captured_at", "id"], unique=False
    )
    op.create_index(
        "ix_mrs_project_captured",
        "management_report_snapshots",
        ["project_id", "captured_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_mrs_scope_captured",
        "management_report_snapshots",
        ["scope_type", "captured_at", "id"],
        unique=False,
    )
    op.create_table(
        "management_report_snapshot_projects",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_management_report_snapshot_projects_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["management_report_snapshots.id"],
            name=op.f(
                "fk_management_report_snapshot_projects_snapshot_id_management_report_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "project_id", name=op.f("pk_management_report_snapshot_projects")
        ),
    )
    op.create_index(
        "ix_mrsp_project_snapshot",
        "management_report_snapshot_projects",
        ["project_id", "snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
        CREATE FUNCTION management_report_immutable() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
            RAISE EXCEPTION 'Management reporting snapshots and scope are immutable';
        END; $$
    """)
    for table in ("management_report_snapshots", "management_report_snapshot_projects"):
        op.execute(
            f"CREATE TRIGGER management_report_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION management_report_immutable()"
        )
    # Deferring the equality check allows a header and its scope to be inserted
    # atomically, but forbids later scope INSERTs as well as partial documents.
    op.execute("""
        CREATE FUNCTION management_report_scope_complete() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE sid uuid; report management_report_snapshots; actual uuid[]; expected uuid[];
        BEGIN
            IF TG_TABLE_NAME = 'management_report_snapshots' THEN sid := NEW.id;
            ELSE sid := NEW.snapshot_id; END IF;
            SELECT * INTO STRICT report FROM management_report_snapshots WHERE id = sid;
            SELECT array_agg(project_id ORDER BY project_id) INTO actual
                FROM management_report_snapshot_projects WHERE snapshot_id = sid;
            SELECT array_agg((p->>'project_id')::uuid ORDER BY (p->>'project_id')::uuid)
                INTO expected FROM jsonb_array_elements(report.payload->'projects') p;
            IF actual IS NULL OR expected IS NULL OR actual IS DISTINCT FROM expected
                OR cardinality(actual) <> report.project_count
                OR (report.scope_type = 'project' AND actual <> ARRAY[report.project_id]) THEN
                RAISE EXCEPTION
                    'Management reporting scope must exactly match the captured projects';
            END IF;
            RETURN NEW;
        END; $$
    """)
    for table in ("management_report_snapshots", "management_report_snapshot_projects"):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER management_report_scope_complete AFTER INSERT ON {table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION management_report_scope_complete()"
        )


def downgrade() -> None:
    """Revert this revision."""
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM management_report_snapshots)
            OR EXISTS (SELECT 1 FROM management_report_snapshot_projects) THEN
            RAISE EXCEPTION 'Retained management snapshots block downgrade';
        END IF;
    END $$""")
    for table in ("management_report_snapshot_projects", "management_report_snapshots"):
        op.execute(f"DROP TRIGGER management_report_scope_complete ON {table}")
        op.execute(f"DROP TRIGGER management_report_immutable ON {table}")
    op.execute("DROP FUNCTION management_report_scope_complete()")
    op.execute("DROP FUNCTION management_report_immutable()")
    op.drop_index("ix_mrsp_project_snapshot", table_name="management_report_snapshot_projects")
    op.drop_table("management_report_snapshot_projects")
    op.drop_index("ix_mrs_scope_captured", table_name="management_report_snapshots")
    op.drop_index("ix_mrs_project_captured", table_name="management_report_snapshots")
    op.drop_index("ix_mrs_captured", table_name="management_report_snapshots")
    op.drop_table("management_report_snapshots")
    # ### end Alembic commands ###
