"use client";

import { useCallback, useEffect, useState } from "react";
import { ApiError, commissions } from "@/lib/api";
import type { CommissionEligibleSale, CommissionGrant } from "@/lib/api";
import { money, percent } from "@/lib/format";
import { COMMISSION_PREPARERS, COMMISSION_RELEASERS, hasAnyRole } from "@/lib/roles";
import type { Roles } from "@/lib/roles";
import { sectionDescription } from "@/components/shell/navigation";
import { Badge, Button, ButtonRow, Card, EmptyState, Field, FieldRow, FormDialog, MoneyInput, Notice, PageHeader, PromptDialog, RateInput, TableScroll } from "@/components/ui";

export function CommissionsTab({ projectId, roles, userId, currencyCodes }: { projectId: string; roles: Roles; userId: string; currencyCodes: Record<string, string> }) {
  const [rows, setRows] = useState<CommissionGrant[]>([]); const [eligible, setEligible] = useState<CommissionEligibleSale[]>([]); const [selected, setSelected] = useState<CommissionGrant | null>(null); const [dialog, setDialog] = useState<"grant" | "allocation" | "reverse" | null>(null); const [error, setError] = useState<string | null>(null);
  const canPrepare = hasAnyRole(roles, COMMISSION_PREPARERS); const canRelease = hasAnyRole(roles, COMMISSION_RELEASERS);
  const load = useCallback(async () => { try { const [grants, sales] = await Promise.all([commissions.list(projectId), commissions.eligibleSales(projectId)]); setRows(grants); setEligible(sales); setSelected((old) => grants.find((x) => x.id === old?.id) ?? old); setError(null); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load commissions."); } }, [projectId]);
  useEffect(() => { void (async () => { await load(); })(); }, [load]); const run = async (fn: () => Promise<unknown>) => { try { await fn(); setDialog(null); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : "That action could not be completed."); } };
  return <div className="stack"><PageHeader title="Commissions" subtitle={sectionDescription("commissions")} actions={canPrepare && eligible.length ? <Button variant="primary" onClick={() => setDialog("grant")}>Prepare commission</Button> : undefined} />
    <Notice tone="info">Beneficiary percentages apply directly to the commissionable base. Releasing this distribution does not change Unit Economics, the sale price, or project cash.</Notice>{error ? <Notice tone="error">{error}</Notice> : null}
    <Card flush>{rows.length ? <TableScroll label="Commission register" compact><thead><tr><th>Unit</th><th>Buyer</th><th className="num">Sold price</th><th className="num">Commission base</th><th className="num">Granted</th><th className="num">Commission total</th><th>Status</th></tr></thead><tbody>{rows.map((x) => <tr key={x.id} onClick={() => setSelected(x)}><th scope="row"><button className="link-button" onClick={() => setSelected(x)}>{x.unit_reference}</button></th><td>{x.buyer_display}</td><td className="num">{money(x.sold_price_snapshot, currencyCodes[x.currency_id])}</td><td className="num">{money(x.commissionable_base_amount, currencyCodes[x.currency_id])}</td><td className="num">{percent(x.granted_rate_fraction)}</td><td className="num">{money(x.commission_total, currencyCodes[x.currency_id])}</td><td><Badge>{x.status}</Badge></td></tr>)}</tbody></TableScroll> : <div className="card-body"><EmptyState title="No commission grants" hint="Prepare one from an active sold contract." /></div>}</Card>
    {selected ? <Card title={`${selected.unit_reference} commission`}><p>{selected.sale_reference} · {selected.buyer_display}</p><p><strong>{percent(selected.granted_rate_fraction)}</strong> granted / <strong>{percent(selected.allocation_rate_total)}</strong> distributed · {money(selected.commission_total, currencyCodes[selected.currency_id])} / {money(selected.allocation_amount_total, currencyCodes[selected.currency_id])}</p><TableScroll label="Beneficiary distribution" compact><thead><tr><th>Beneficiary</th><th className="num">Rate against base</th><th className="num">Calculated amount</th></tr></thead><tbody>{selected.allocations.map((a) => <tr key={a.id}><th scope="row">{a.beneficiary_name}</th><td className="num">{percent(a.rate_fraction)}</td><td className="num">{money(a.calculated_amount, currencyCodes[selected.currency_id])}</td></tr>)}</tbody></TableScroll><ButtonRow>{canPrepare && selected.status === "draft" ? <Button onClick={() => setDialog("allocation")}>Add beneficiary</Button> : null}{canRelease && selected.status === "draft" && selected.is_reconciled && selected.prepared_by_user_id !== userId ? <Button variant="primary" onClick={() => void run(() => commissions.release(projectId, selected.id))}>Release</Button> : null}{canRelease && selected.status === "released" ? <Button variant="danger" onClick={() => setDialog("reverse")}>Reverse commission</Button> : null}</ButtonRow></Card> : null}
    {dialog === "grant" ? <GrantDialog sales={eligible} codes={currencyCodes} onCancel={() => setDialog(null)} onSubmit={(body) => void run(() => commissions.create(projectId, body))} /> : null}
    {dialog === "allocation" && selected ? <AllocationDialog onCancel={() => setDialog(null)} onSubmit={(body) => void run(() => commissions.addAllocation(projectId, selected.id, body))} /> : null}
    {dialog === "reverse" && selected ? <PromptDialog title="Reverse commission" label="Reason" hint="This preserves the released record and does not change the sale price, Unit Economics or confirmed project cash." confirmLabel="Reverse" onCancel={() => setDialog(null)} onSubmit={(reason) => void run(() => commissions.reverse(projectId, selected.id, reason))} /> : null}
  </div>;
}
function GrantDialog({ sales, codes, onCancel, onSubmit }: { sales: CommissionEligibleSale[]; codes: Record<string, string>; onCancel: () => void; onSubmit: (body: Record<string, unknown>) => void }) { const [sale, setSale] = useState(sales[0]?.id ?? ""); const chosen = sales.find((x) => x.id === sale); const [base, setBase] = useState(""); const [rate, setRate] = useState(""); return <FormDialog title="Prepare commission" confirmLabel="Save draft" disabled={!sale || !base || !rate} onCancel={onCancel} onSubmit={() => onSubmit({ sale_contract_id: sale, commissionable_base_amount: base, granted_rate_fraction: rate })}><Field label="Sold contract"><select className="input" value={sale} onChange={(e) => setSale(e.target.value)}>{sales.map((x) => <option key={x.id} value={x.id}>{x.unit_reference} · {x.buyer_display} · {money(x.sold_price, codes[x.currency_id])}</option>)}</select></Field><FieldRow><Field label="Commissionable base"><MoneyInput code={chosen ? codes[chosen.currency_id] : null} value={base} onChange={setBase} /></Field><Field label="Granted commission percentage"><RateInput value={rate} onChange={setRate} /></Field></FieldRow></FormDialog>; }
function AllocationDialog({ onCancel, onSubmit }: { onCancel: () => void; onSubmit: (body: Record<string, unknown>) => void }) { const [name, setName] = useState(""); const [rate, setRate] = useState(""); return <FormDialog title="Add beneficiary" description="This percentage applies directly to the commissionable base, not as a share of the commission pool." confirmLabel="Add beneficiary" disabled={!name || !rate} onCancel={onCancel} onSubmit={() => onSubmit({ beneficiary_name: name, rate_fraction: rate })}><Field label="Beneficiary name"><input className="input" value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Beneficiary percentage against base"><RateInput value={rate} onChange={setRate} /></Field></FormDialog>; }
